image:
  name: docker/compose
  entrypoint: ["/bin/sh", "-c"]

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  only:
   - master
  script:
   - docker-compose stop
   - docker-compose build
   - docker-compose up -d
